name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 기본 브랜치가 main이라고 가정합니다. master를 사용하는 경우 이를 변경하세요.
  # 수동으로 워크플로우를 실행할 수 있게 해줍니다
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm' # package manager를 pnpm으로 변경했습니다

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build website
        run: pnpm build

      # GitHub Pages에 배포하기
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # docusaurus의 기본 build 출력 디렉토리
          publish_dir: ./build
          # Git 사용자 정보
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
